version: '3'
services:
  nginx_reactjs_app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    ports:
      - "3335:3335"
      - "3337:3337"
    volumes:
      - ../src:/var/www/html
      - /var/www/html/node_modules
    stdin_open: true
    tty: true
    environment:
    - CHOKIDAR_USEPOLLING=true
    - WATCHPACK_POLLING=true